print("VE işlemi")
print("1 ve 1 = " + str((True) and (True)))
print("1 ve 0 = " + str((True) and (False)))
print("0 ve 1 = " + str((False) and (True)))
print("0 ve 0 = " + str((False) and (False)))
print("VEYA işlemi")
print("1 veya 1 = " + str((True) or (True)))
print("1 veya 0 = " + str((True) or (False)))
print("0 veya 1 = " + str((False) or (True)))
print("0 veya 0 = " + str((False) or (False)))
print("Değil işlemi")
print("1 in değili = " + str((1 != 1)))
print("0'ın değili = " + str((0 != 1)))
